// <auto-generated />
namespace Logs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vasiliystan_8545639ffb864cb68b5d4d1baf5943ba : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vasiliystan_8545639ffb864cb68b5d4d1baf5943ba));
        
        string IMigrationMetadata.Id
        {
            get { return "201802172149590_vasiliy.stan_8545639ffb864cb68b5d4d1baf5943ba"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
