// <auto-generated />
namespace Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vasiliystan_9dc0430cf2cd43eba6af748007b63d9e : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vasiliystan_9dc0430cf2cd43eba6af748007b63d9e));
        
        string IMigrationMetadata.Id
        {
            get { return "201802161447559_vasiliy.stan_9dc0430cf2cd43eba6af748007b63d9e"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
