#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\DetailsUser\Index.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\DetailsUser\Index.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\DetailsUser\Index.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\DetailsUser\Index.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/DetailsUser/Index.cshtml")]
    public partial class _DetailsUser_Index_cshtml : System.Web.Mvc.WebViewPage<Modules.Site.DetailsUser.DetailsUserModel>
    {
        public _DetailsUser_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\DetailsUser\Index.cshtml"
  
    Layout = "~/DetailsPages.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("pagetitle", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\DetailsUser\Index.cshtml"
Write(I18NEngine.GetMvcHtmlString("modules.site.detailsuser.index", "title"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

            
            #line 15 "..\..\DetailsUser\Index.cshtml"
  
    var selectableValue = string.Empty;
    var actionName = Model.IsUpdate ? "update" : "create";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("bodyscripts", () => {

WriteLiteral("\r\n    <script>\r\n        $(\"#base-roles\").multiSelect({ keepOrder: true });\r\n    <" +
"/script>\r\n    <script>\r\n        $(document).ready(function () {\r\n            $(\'" +
"#user-button-");

            
            #line 27 "..\..\DetailsUser\Index.cshtml"
                       Write(actionName);

            
            #line default
            #line hidden
WriteLiteral(@"').on('click', function (e) {
                var baseRolesValues = [];
                $(""#base-roles :selected"").each(function(index) { baseRolesValues.push($(this).val()); });
                console.log(baseRolesValues);
                $.Site.Libraries.Common.Preloader.Show();
                $.Site.Libraries.WebApi.Common.ExecuteAction({
                    uri: $(""#webapi-identity-user-");

            
            #line 33 "..\..\DetailsUser\Index.cshtml"
                                             Write(actionName);

            
            #line default
            #line hidden
WriteLiteral(@""").attr(""href""),
                    data:
                    {
                        UserName: $(""#input-user-name"").val(),
                        Description: $(""#input-description"").val(),
                        Email: $(""#input-email"").val(),
                        Note: $(""#input-note"").val(),
                        BaseRoles: baseRolesValues 
                    },
                    onAfterAction: function () {
                        var reloadUri = $(""#reload-uri"").attr(""href"");
                        window.location = reloadUri;
                    }
                });
            });

        });
    </script>
");

});

WriteLiteral("\r\n<a");

WriteLiteral(" id=\"webapi-identity-user-create\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1750), Tuple.Create("\"", 1782)
, Tuple.Create(Tuple.Create("", 1757), Tuple.Create<System.Object, System.Int32>(Href("~/api/identity/createuser")
, 1757), false)
);

WriteLiteral("></a>\r\n<a");

WriteLiteral(" id=\"webapi-identity-user-update\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1840), Tuple.Create("\"", 1872)
, Tuple.Create(Tuple.Create("", 1847), Tuple.Create<System.Object, System.Int32>(Href("~/api/identity/updateuser")
, 1847), false)
);

WriteLiteral("></a>\r\n<a");

WriteLiteral(" id=\"reload-uri\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1913), Tuple.Create("\"", 1954)
            
            #line 55 "..\..\DetailsUser\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1920), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "TotalUsers")
            
            #line default
            #line hidden
, 1920), false)
);

WriteLiteral("></a>\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">          \r\n        <div");

WriteLiteral(" class=\"col-md-offset-4 col-md-4 padding-top-15\"");

WriteLiteral(">\r\n            <form");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"input-user-name\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 2225), Tuple.Create("\"", 2332)
            
            #line 61 "..\..\DetailsUser\Index.cshtml"
  , Tuple.Create(Tuple.Create("", 2239), Tuple.Create<System.Object, System.Int32>(I18NEngine.GetMvcHtmlString("modules.site.detailsuser.index", "placeholder_input_user_name")
            
            #line default
            #line hidden
, 2239), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 2333), Tuple.Create("\"", 2366)
            
            #line 61 "..\..\DetailsUser\Index.cshtml"
                                                                                                        , Tuple.Create(Tuple.Create("", 2341), Tuple.Create<System.Object, System.Int32>(Html.Raw(Model.UserName)
            
            #line default
            #line hidden
, 2341), false)
);

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"input-description\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 2507), Tuple.Create("\"", 2616)
            
            #line 64 "..\..\DetailsUser\Index.cshtml"
    , Tuple.Create(Tuple.Create("", 2521), Tuple.Create<System.Object, System.Int32>(I18NEngine.GetMvcHtmlString("modules.site.detailsuser.index", "placeholder_input_description")
            
            #line default
            #line hidden
, 2521), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 2617), Tuple.Create("\"", 2653)
            
            #line 64 "..\..\DetailsUser\Index.cshtml"
                                                                                                            , Tuple.Create(Tuple.Create("", 2625), Tuple.Create<System.Object, System.Int32>(Html.Raw(Model.Description)
            
            #line default
            #line hidden
, 2625), false)
);

WriteLiteral(" />\r\n                </div> \r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"input-email\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 2790), Tuple.Create("\"", 2893)
            
            #line 67 "..\..\DetailsUser\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2804), Tuple.Create<System.Object, System.Int32>(I18NEngine.GetMvcHtmlString("modules.site.detailsuser.index", "placeholder_input_email")
            
            #line default
            #line hidden
, 2804), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 2894), Tuple.Create("\"", 2924)
            
            #line 67 "..\..\DetailsUser\Index.cshtml"
                                                                                                , Tuple.Create(Tuple.Create("", 2902), Tuple.Create<System.Object, System.Int32>(Html.Raw(Model.Email)
            
            #line default
            #line hidden
, 2902), false)
);

WriteLiteral(" />\r\n                </div> \r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"input-note\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 3060), Tuple.Create("\"", 3162)
            
            #line 70 "..\..\DetailsUser\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3074), Tuple.Create<System.Object, System.Int32>(I18NEngine.GetMvcHtmlString("modules.site.detailsuser.index", "placeholder_input_note")
            
            #line default
            #line hidden
, 3074), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 3163), Tuple.Create("\"", 3192)
            
            #line 70 "..\..\DetailsUser\Index.cshtml"
                                                                                              , Tuple.Create(Tuple.Create("", 3171), Tuple.Create<System.Object, System.Int32>(Html.Raw(Model.Note)
            
            #line default
            #line hidden
, 3171), false)
);

WriteLiteral("/>\r\n                </div>                \r\n            </form>\r\n        </div>\r\n" +
"    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-4 col-md-4\"");

WriteLiteral(">\r\n            <label>");

            
            #line 77 "..\..\DetailsUser\Index.cshtml"
              Write(I18NEngine.GetMvcHtmlString("modules.site.detailsuser.index", "label_select_role_group"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <select");

WriteLiteral(" id=\"base-roles\"");

WriteLiteral(" multiple=\"multiple\"");

WriteLiteral(">\r\n");

            
            #line 79 "..\..\DetailsUser\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 79 "..\..\DetailsUser\Index.cshtml"
                 foreach (var baseRole in Model.Roles)
                {
                    
            
            #line default
            #line hidden
            
            #line 81 "..\..\DetailsUser\Index.cshtml"
                      
                         selectableValue = baseRole.IsSelectable ? "selected=\"selected\"" : "";
                     
            
            #line default
            #line hidden
            
            #line 83 "..\..\DetailsUser\Index.cshtml"
                      

            
            #line default
            #line hidden
WriteLiteral("                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 3781), Tuple.Create("\"", 3807)
            
            #line 84 "..\..\DetailsUser\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3789), Tuple.Create<System.Object, System.Int32>(baseRole.RoleName
            
            #line default
            #line hidden
, 3789), false)
);

WriteLiteral(" ");

            
            #line 84 "..\..\DetailsUser\Index.cshtml"
                                                  Write(selectableValue);

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 84 "..\..\DetailsUser\Index.cshtml"
                                                                   Write(baseRole.RoleName);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 85 "..\..\DetailsUser\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </select>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-4 col-md-4 padding-top-15\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-offset-8 col-md-4\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("id", Tuple.Create(" id=\"", 4120), Tuple.Create("\"", 4148)
, Tuple.Create(Tuple.Create("", 4125), Tuple.Create("user-button-", 4125), true)
            
            #line 93 "..\..\DetailsUser\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4137), Tuple.Create<System.Object, System.Int32>(actionName
            
            #line default
            #line hidden
, 4137), false)
);

WriteLiteral(" class=\"btn btn-primary col-md-12 text-align-left\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-fw\"");

WriteLiteral(">");

            
            #line 94 "..\..\DetailsUser\Index.cshtml"
                                       Write(I18NEngine.GetMvcHtmlString("modules.site.detailsuser.index", $"button_{actionName}"));

            
            #line default
            #line hidden
WriteLiteral("</i>\r\n                    </a>                                                   " +
"             \r\n                </div>\r\n            </div>\r\n        </div>       " +
" \r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
