#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\TotalPages.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 2 "..\..\TotalPages.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\TotalPages.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/TotalPages.cshtml")]
    public partial class _TotalPages_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _TotalPages_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n        <title>\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\TotalPages.cshtml"
       Write(RenderSection("pagetitle", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </title>\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 406), Tuple.Create("\"", 498)
, Tuple.Create(Tuple.Create("", 413), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/bootstrap/css/bootstrap.min" +
".css")
, 413), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 532), Tuple.Create("\"", 620)
, Tuple.Create(Tuple.Create("", 539), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.css" +
"")
, 539), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 654), Tuple.Create("\"", 758)
, Tuple.Create(Tuple.Create("", 661), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables-plugins/dataTabl" +
"es.bootstrap.css")
, 661), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 792), Tuple.Create("\"", 900)
, Tuple.Create(Tuple.Create("", 799), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables-responsive/dataT" +
"ables.responsive.css")
, 799), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 934), Tuple.Create("\"", 1011)
, Tuple.Create(Tuple.Create("", 941), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css")
, 941), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1045), Tuple.Create("\"", 1143)
, Tuple.Create(Tuple.Create("", 1052), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/font-awesome/css/font-aweso" +
"me.min.css")
, 1052), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src=""https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js""></script>
            <script src=""https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js""></script>
        <![endif]-->
");

WriteLiteral("        ");

            
            #line 26 "..\..\TotalPages.cshtml"
   Write(Styles.Render("~/Libraries/Common/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\TotalPages.cshtml"
   Write(Styles.Render("~/Libraries/Components/Preloader/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1737), Tuple.Create("\"", 1817)
, Tuple.Create(Tuple.Create("", 1743), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js")
, 1743), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\TotalPages.cshtml"
   Write(Scripts.Render("~/Libraries/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 31 "..\..\TotalPages.cshtml"
   Write(Scripts.Render("~/Libraries/Components/WebApi/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\TotalPages.cshtml"
   Write(Scripts.Render("~/Libraries/Components/WebApi/Common/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body>\r\n        <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">        \r\n            <div");

WriteLiteral(" id=\"status\"");

WriteLiteral(">&nbsp;</div>\r\n        </div>    \r\n        <div");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\TotalPages.cshtml"
               Write(Html.ActionLink(I18NEngine.GetString("modules.layouts.totalpages", "navbar_brand_link"), "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 43 "..\..\TotalPages.cshtml"
                
            
            #line default
            #line hidden
            
            #line 43 "..\..\TotalPages.cshtml"
                 if (User.Identity.IsAuthenticated)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"navbar-header navbar-right\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 46 "..\..\TotalPages.cshtml"
                   Write(Html.ActionLink(I18NEngine.GetString("modules.layouts.totalpages", "exit_link"), "Logout", "Accounts", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>                    \r\n");

            
            #line 48 "..\..\TotalPages.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n\r\n");

WriteLiteral("        ");

            
            #line 52 "..\..\TotalPages.cshtml"
   Write(RenderPage("~/Sidebar.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n");

WriteLiteral("        ");

            
            #line 54 "..\..\TotalPages.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2992), Tuple.Create("\"", 3081)
, Tuple.Create(Tuple.Create("", 2998), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.min." +
"js")
, 2998), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3109), Tuple.Create("\"", 3195)
, Tuple.Create(Tuple.Create("", 3115), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.js")
, 3115), false)
);

WriteLiteral("></script>\r\n\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3225), Tuple.Create("\"", 3323)
, Tuple.Create(Tuple.Create("", 3231), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables/js/jquery.dataTa" +
"bles.min.js")
, 3231), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3351), Tuple.Create("\"", 3457)
, Tuple.Create(Tuple.Create("", 3357), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables-plugins/dataTabl" +
"es.bootstrap.min.js")
, 3357), false)
);

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3485), Tuple.Create("\"", 3591)
, Tuple.Create(Tuple.Create("", 3491), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/vendor/datatables-responsive/dataT" +
"ables.responsive.js")
, 3491), false)
);

WriteLiteral("></script>\r\n\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3621), Tuple.Create("\"", 3695)
, Tuple.Create(Tuple.Create("", 3627), Tuple.Create<System.Object, System.Int32>(Href("~/Themes/Themes.Core/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js")
, 3627), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("        ");

            
            #line 63 "..\..\TotalPages.cshtml"
   Write(RenderSection("bodyscripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 64 "..\..\TotalPages.cshtml"
   Write(Scripts.Render("~/Libraries/Components/Preloader/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
