#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\TotalUsers\Index.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\TotalUsers\Index.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\TotalUsers\Index.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\TotalUsers\Index.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/TotalUsers/Index.cshtml")]
    public partial class _TotalUsers_Index_cshtml : System.Web.Mvc.WebViewPage<Modules.Site.TotalUsers.TotalUsersModel>
    {
        public _TotalUsers_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\TotalUsers\Index.cshtml"
  
    Layout = "~/TotalPages.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("pagetitle", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\TotalUsers\Index.cshtml"
Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "title"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("bodyscripts", () => {

WriteLiteral(@"
    <script>
        $(document).ready(function() {
            $('#dataTables-total-users').DataTable({
                responsive: true
            });
        });
    </script>  
    <script>

        $(document).ready(function () {

            $('#dataTables-total-users').on('click', '.btn-delete-user', function(e) {
                    var userName = $(e.currentTarget).data('user-name');
                    localStorage.setItem(""delete-user-name"", userName);
                });

            $('#confirmDeleteUser').on('click', '.btn-yes', function (e) {
                $.Site.Libraries.Common.Preloader.Show();
                $.Site.Libraries.WebApi.Common.ExecuteAction({
                    uri: $(""#webapi-identity-deleteuser"").attr(""href""),
                    data:
                    {
                        UserName: localStorage.getItem(""delete-user-name"")
                    },
                    onAfterAction: function () { window.location.reload(false);}
                });
            });

        });

    </script>
");

});

WriteLiteral("\r\n<a");

WriteLiteral(" id=\"webapi-identity-deleteuser\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1463), Tuple.Create("\"", 1495)
, Tuple.Create(Tuple.Create("", 1470), Tuple.Create<System.Object, System.Int32>(Href("~/api/identity/deleteuser")
, 1470), false)
);

WriteLiteral("></a>\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    \r\n    <div");

WriteLiteral(" id=\"confirmDeleteUser\"");

WriteLiteral(" class=\"col-md-offset-2 col-md-8 modal fade\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Cancel\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</span>\r\n                    </button>                    \r\n                   " +
" <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">");

            
            #line 61 "..\..\TotalUsers\Index.cshtml"
                                       Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "confirmdeleteuser_modal_title"));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-body text-align-center\"");

WriteLiteral(">");

            
            #line 63 "..\..\TotalUsers\Index.cshtml"
                                                     Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "confirmdeleteuser_modal_message"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-primary btn-yes\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">");

            
            #line 65 "..\..\TotalUsers\Index.cshtml"
                                                                                          Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "confirmdeleteuser_modal_button_yes"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Cancel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">");

            
            #line 66 "..\..\TotalUsers\Index.cshtml"
                                                                                                      Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "confirmdeleteuser_modal_button_cancel"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>    \r" +
"\n    \r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-9 text-align-center h4\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 78 "..\..\TotalUsers\Index.cshtml"
                       Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "name_table"));

            
            #line default
            #line hidden
WriteLiteral("                            \r\n                        </div>                     " +
"   \r\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-offset-7 col-md-5\"");

WriteLiteral(">\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3497), Tuple.Create("\"", 3537)
            
            #line 83 "..\..\TotalUsers\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3504), Tuple.Create<System.Object, System.Int32>(Url.Action("New", "DetailsUser")
            
            #line default
            #line hidden
, 3504), false)
);

WriteLiteral(" class=\"btn btn-primary col-md-12 text-align-left\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-fw fa-plus\"");

WriteLiteral(">");

            
            #line 84 "..\..\TotalUsers\Index.cshtml"
                                                               Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "button_new"));

            
            #line default
            #line hidden
WriteLiteral(@"</i>
                                    </a>                                                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

WriteLiteral(" id=\"dataTables-total-users\"");

WriteLiteral(">\r\n                        <thead>\r\n                            <tr>\r\n           " +
"                     <th");

WriteLiteral(" class=\"col-md-2 text-center\"");

WriteLiteral(">");

            
            #line 96 "..\..\TotalUsers\Index.cshtml"
                                                            Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "th_name"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th");

WriteLiteral(" class=\"col-md-2 text-center\"");

WriteLiteral(">");

            
            #line 97 "..\..\TotalUsers\Index.cshtml"
                                                            Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "th_email"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th");

WriteLiteral(" class=\"col-md-2 text-center\"");

WriteLiteral(">");

            
            #line 98 "..\..\TotalUsers\Index.cshtml"
                                                            Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "th_description"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th");

WriteLiteral(" class=\"col-md-2 text-center\"");

WriteLiteral(">");

            
            #line 99 "..\..\TotalUsers\Index.cshtml"
                                                            Write(I18NEngine.GetMvcHtmlString("modules.site.totalusers.index", "th_note"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th");

WriteLiteral(" class=\"col-md-2 text-center\"");

WriteLiteral("></th>\r\n                            </tr>\r\n                        </thead>\r\n    " +
"                    <tbody>\r\n");

            
            #line 104 "..\..\TotalUsers\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 104 "..\..\TotalUsers\Index.cshtml"
                               var index = 0;
            
            #line default
            #line hidden
WriteLiteral("    \r\n");

            
            #line 105 "..\..\TotalUsers\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 105 "..\..\TotalUsers\Index.cshtml"
                             foreach (var user in Model.Users)
                            {
                                index++;
                                var trClass = index % 2 == 1 ? "even" : "odd";

            
            #line default
            #line hidden
WriteLiteral("                                <tr");

WriteAttribute("class", Tuple.Create(" class=\"", 5344), Tuple.Create("\"", 5367)
            
            #line 109 "..\..\TotalUsers\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5352), Tuple.Create<System.Object, System.Int32>(trClass
            
            #line default
            #line hidden
, 5352), false)
, Tuple.Create(Tuple.Create(" ", 5360), Tuple.Create("gradeA", 5361), true)
);

WriteLiteral(">\r\n                                    <td");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">");

            
            #line 110 "..\..\TotalUsers\Index.cshtml"
                                                    Write(user.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">");

            
            #line 111 "..\..\TotalUsers\Index.cshtml"
                                                    Write(user.Email);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">");

            
            #line 112 "..\..\TotalUsers\Index.cshtml"
                                                    Write(user.Description);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">");

            
            #line 113 "..\..\TotalUsers\Index.cshtml"
                                                    Write(user.Note);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td");

WriteLiteral(" class=\"col-md-2 text-center\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5788), Tuple.Create("\"", 5871)
            
            #line 115 "..\..\TotalUsers\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5795), Tuple.Create<System.Object, System.Int32>(Url.Action("Update", "DetailsUser", new {userName = Url.Encode(user.Name)})
            
            #line default
            #line hidden
, 5795), false)
);

WriteLiteral(" class=\"blue\"");

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"fa fa-fw fa-pencil\"");

WriteLiteral("></i>\r\n                                        </a>\r\n                            " +
"            <a");

WriteLiteral(" class=\"red btn-delete-user\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#confirmDeleteUser\"");

WriteLiteral(" data-user-name=\"");

            
            #line 118 "..\..\TotalUsers\Index.cshtml"
                                                                                                                                       Write(user.Name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"fa fa-fw fa-trash-o\"");

WriteLiteral("></i>\r\n                                        </a>\r\n                            " +
"        </td>\r\n                                </tr>                            " +
"\r\n");

            
            #line 123 "..\..\TotalUsers\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral(@"                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>

</div>");

        }
    }
}
#pragma warning restore 1591
