#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\DetailsRole\Index.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\DetailsRole\Index.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\DetailsRole\Index.cshtml"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\DetailsRole\Index.cshtml"
    using Translations;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/DetailsRole/Index.cshtml")]
    public partial class _DetailsRole_Index_cshtml : System.Web.Mvc.WebViewPage<Modules.Site.DetailsRole.DetailsRoleModel>
    {
        public _DetailsRole_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\DetailsRole\Index.cshtml"
  
    Layout = "~/DetailsPages.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("pagetitle", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\DetailsRole\Index.cshtml"
Write(I18NEngine.GetMvcHtmlString("modules.site.detailsrole.index", "title"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

            
            #line 15 "..\..\DetailsRole\Index.cshtml"
  
    var selectableValue = string.Empty;
    var actionName = Model.IsUpdate ? "update" : "create";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("bodyscripts", () => {

WriteLiteral("\r\n    <script>\r\n        $(\"#base-roles\").multiSelect({ keepOrder: true });\r\n    <" +
"/script>\r\n    <script>\r\n        $(document).ready(function () {\r\n            $(\'" +
"#role-button-");

            
            #line 27 "..\..\DetailsRole\Index.cshtml"
                       Write(actionName);

            
            #line default
            #line hidden
WriteLiteral(@"').on('click', function (e) {
                var baseRolesValues = [];
                $(""#base-roles :selected"").each(function(index) { baseRolesValues.push($(this).val()); });
                console.log(baseRolesValues);
                $.Site.Libraries.Common.Preloader.Show();
                $.Site.Libraries.WebApi.Common.ExecuteAction({
                    uri: $(""#webapi-identity-role-");

            
            #line 33 "..\..\DetailsRole\Index.cshtml"
                                             Write(actionName);

            
            #line default
            #line hidden
WriteLiteral(@""").attr(""href""),
                    data:
                    {
                        RoleName: $(""#input-role-name"").val(),
                        BaseRoles: baseRolesValues 
                    },
                    onAfterAction: function () {
                        var reloadUri = $(""#reload-uri"").attr(""href"");
                        window.location = reloadUri;
                    }
                });
            });

        });
    </script>
");

});

WriteLiteral("\r\n<a");

WriteLiteral(" id=\"webapi-identity-role-create\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1569), Tuple.Create("\"", 1598)
, Tuple.Create(Tuple.Create("", 1576), Tuple.Create<System.Object, System.Int32>(Href("~/api/identity/addrole")
, 1576), false)
);

WriteLiteral("></a>\r\n<a");

WriteLiteral(" id=\"webapi-identity-role-update\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1656), Tuple.Create("\"", 1688)
, Tuple.Create(Tuple.Create("", 1663), Tuple.Create<System.Object, System.Int32>(Href("~/api/identity/updaterole")
, 1663), false)
);

WriteLiteral("></a>\r\n<a");

WriteLiteral(" id=\"reload-uri\"");

WriteLiteral(" class=\"hidden\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1729), Tuple.Create("\"", 1770)
            
            #line 52 "..\..\DetailsRole\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1736), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "TotalRoles")
            
            #line default
            #line hidden
, 1736), false)
);

WriteLiteral("></a>\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">          \r\n        <div");

WriteLiteral(" class=\"col-md-offset-4 col-md-4 padding-top-15\"");

WriteLiteral(">\r\n            <form");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"input-role-name\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 2041), Tuple.Create("\"", 2148)
            
            #line 58 "..\..\DetailsRole\Index.cshtml"
  , Tuple.Create(Tuple.Create("", 2055), Tuple.Create<System.Object, System.Int32>(I18NEngine.GetMvcHtmlString("modules.site.detailsrole.index", "placeholder_input_role_name")
            
            #line default
            #line hidden
, 2055), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 2149), Tuple.Create("\"", 2182)
            
            #line 58 "..\..\DetailsRole\Index.cshtml"
                                                                                                        , Tuple.Create(Tuple.Create("", 2157), Tuple.Create<System.Object, System.Int32>(Html.Raw(Model.RoleName)
            
            #line default
            #line hidden
, 2157), false)
);

WriteLiteral("/>\r\n                </div>                         \r\n            </form>\r\n       " +
" </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-4 col-md-4\"");

WriteLiteral(">\r\n            <label>");

            
            #line 65 "..\..\DetailsRole\Index.cshtml"
              Write(I18NEngine.GetMvcHtmlString("modules.site.detailsrole.index", "label_select_role_group"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <select");

WriteLiteral(" id=\"base-roles\"");

WriteLiteral(" multiple=\"multiple\"");

WriteLiteral(">\r\n");

            
            #line 67 "..\..\DetailsRole\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 67 "..\..\DetailsRole\Index.cshtml"
                 foreach (var baseRole in Model.Roles)
                {
                    
            
            #line default
            #line hidden
            
            #line 69 "..\..\DetailsRole\Index.cshtml"
                      
                         selectableValue = baseRole.IsSelectable ? "selected=\"selected\"" : "";
                     
            
            #line default
            #line hidden
            
            #line 71 "..\..\DetailsRole\Index.cshtml"
                      

            
            #line default
            #line hidden
WriteLiteral("                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2780), Tuple.Create("\"", 2806)
            
            #line 72 "..\..\DetailsRole\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2788), Tuple.Create<System.Object, System.Int32>(baseRole.RoleName
            
            #line default
            #line hidden
, 2788), false)
);

WriteLiteral(" ");

            
            #line 72 "..\..\DetailsRole\Index.cshtml"
                                                  Write(selectableValue);

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 72 "..\..\DetailsRole\Index.cshtml"
                                                                   Write(baseRole.RoleName);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 73 "..\..\DetailsRole\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </select>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-4 col-md-4 padding-top-15\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-offset-8 col-md-4\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("id", Tuple.Create(" id=\"", 3119), Tuple.Create("\"", 3147)
, Tuple.Create(Tuple.Create("", 3124), Tuple.Create("role-button-", 3124), true)
            
            #line 81 "..\..\DetailsRole\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3136), Tuple.Create<System.Object, System.Int32>(actionName
            
            #line default
            #line hidden
, 3136), false)
);

WriteLiteral(" class=\"btn btn-primary col-md-12 text-align-left\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-fw\"");

WriteLiteral(">");

            
            #line 82 "..\..\DetailsRole\Index.cshtml"
                                       Write(I18NEngine.GetMvcHtmlString("modules.site.detailsrole.index", $"button_{actionName}"));

            
            #line default
            #line hidden
WriteLiteral("</i>\r\n                    </a>                                                   " +
"             \r\n                </div>\r\n            </div>\r\n        </div>       " +
" \r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
